### PR TITLE
[Properties] Add spring-configuration-metadata.json with description of properties provided by library

### PR DESCRIPTION
**Pull request by DaNizz97**
Spring allows to describe properties which could be used by library users. It improves understanding of what specific property is used for and gets rid of IDEA warning.

---
Idk your CI/CD processes so I just left version unchanged for now. Pls let me know if I need to take further actions.

### CODE REVIEW

**Comment by nazarovctrl** [comment]
> Spring allows to describe properties which could be used by library users. It improves understanding of what specific property is used for and gets rid of IDEA warning.
> 
> Idk your CI/CD processes so I just left version unchanged for now. Pls let me know if I need to take further actions.

Hi can you send your telegram or linkedin profile

**Review by nazarovctrl — APPROVED** [review]
LGTM

**Comment by DaNizz97** [comment]
@nazarovctrl Hey! JFYI I don't have [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to your repo and cannot merge this PR.

**Comment by DaNizz97** [comment]
[My LinkedIn profile](www.linkedin.com/in/danizz) btw

**Pull request merged**
